### ISSUE TITLE
Faulty table reference

### ISSUE THREAD

**Issue by chaddpaul** [godot-packers/quiz_app#13]
It has a join table called 'student_quizzes', but when we are running our seed file it is looking for a 'quizzes_students' table.

**Comment by phlco** [comment]
The conventions for a pure join table are to take the two tables names, pluralize them and combine them in alphabetical order.

A join table between students and quizzes would then be `students_quizzes` and contain two columns `student_id` and `quiz_id`

**Comment by krismacfarlane** [comment]
So, Q comes before S, meaning quizzes_students, right?

**Comment by phlco** [comment]
@krismacfarlane Exactly. Make sure @chaddpaul learns the alphabet. :v:
