### ISSUE TITLE
Trouble implementing our model relationships into our routes

### ISSUE THREAD

**Issue by krismacfarlane** [godot-packers/quiz_app#22]
We can't show our 'untaken' quizzes based on a students id. Basically, our model relationships aren't transferring over. We changed our ERD based on our convo with Travis yesterday and now it's not really working.

**Comment by phlco** [comment]
Where is your ERD so we can talk about this? 
Please upload one and include all the relevant relationships and what you're planning to do with ActiveRecord.

**Comment by krismacfarlane** [comment]
![erd_1](https://cloud.githubusercontent.com/assets/9731414/6274579/8586e3ee-b846-11e4-9d8a-43e6dcf91608.jpg)

Our schema looks like:

``` ruby
  create_table "answers", force: :cascade do |t|
    t.string  "content"
    t.boolean "is_picked",    default: false
    t.integer "question_id"
  end

  create_table "cohorts", force: :cascade do |t|
    t.string   "name",           null: false
    t.integer  "instructor_id",  null: false
    t.string   "room",           null: false
    t.string   "producer",       null: false
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "instructors", force: :cascade do |t|
    t.string   "name",            null: false
    t.string   "email",           null: false
    t.string   "password_digest"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "questions", force: :cascade do |t|
    t.string  "content"
    t.boolean "got_right",  default: false
    t.integer "points",     default: 0
    t.integer "quiz_id"
  end

  create_table "quizzes", force: :cascade do |t|
    t.string   "name",                       null: false
    t.integer  "grade",      default: 0
    t.boolean  "has_grade",  default: false
    t.boolean  "been_taken", default: false
    t.integer  "cohort_id"
    t.integer  "student_id"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "student_quizzes", force: :cascade do |t|
    t.integer "student_id"
    t.integer "quiz_id"
  end

  create_table "students", force: :cascade do |t|
    t.string   "name",                        null: false
    t.string   "email",                       null: false
    t.string   "password_digest"
    t.integer  "cohort_id",      default: 1
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
```

We want to be able to do:

``` ruby
q = some quiz
q.student.name ==> "Bob"

# this is an additional thing we want to do
student = Student.find(session[:session_id])
if student.cohort_id == q.cohort_id
     do something
end
```

**Comment by phlco** [comment]
Awesome!!

So you have something like the following in your schema: 

``` rb
# some lines removed for brevity.
 create_table "quizzes", force: :cascade do |t|
    t.boolean  "has_grade",  default: false
    t.boolean  "been_taken", default: false
    t.integer  "cohort_id"
    t.integer  "student_id"
  end

  create_table "student_quizzes", force: :cascade do |t|
    t.integer "student_id"
    t.integer "quiz_id"
  end

  create_table "students", force: :cascade do |t|
    t.string   "name",                        null: false
    t.integer  "cohort_id",      default: 1
  end
```

And what you're saying in your ActiveRecord relationships is that there is a pure join table between a student and a quiz. Student `has_and_belongs_to :quizzes` and Quiz `has_and_belongs_to_many :students`

So in that join table `quizzes_students` you're only recording the ids between the two tables, just the pure relationship.  

Then I see that you have "been_taken" (although a better name might be "has_been_taken") which is a boolean and is on the quiz table. That says that many students can take that quiz but that the state of the quiz as being taken or not is the same for all students. 

Does that make sense?  If I take a quiz and you haven't taken it yet, would the quiz table say "has_been_taken" should be true or false for everyone? 

Furthermore that "has_grade" which I'm assuming is like "has_been_graded" ? is the same for all students?

**Comment by krismacfarlane** [comment]
So this is not totally fixed yet, but basically we aren't using that student_quizzes table anymore. We want to serialize the quizzes, so that Quiz 1 would take up the first 10 (or however many students in the cohort) rows in the table and each one would be a different student_id.

QUIZ TABLE:

| id | name | cohort_id | student_id |
| :-- | :-- | :-- | :-- |
| 1 | quiz 1 | 1 | 1 |
| 2 | quiz 1 | 1 | 2 |
| 3 | quiz 2 | 1 | 1 |

Does this make sense?

**Comment by phlco** [comment]
No this doesn't make any sense. Let's talk more about the above quizzes_students table first.

**Comment by krismacfarlane** [comment]
We encountered an issue with that when trying to do a conditional. I can't remember the details of it, but we stopped using it. The table above it kind of working for some reason. We are going to keep trudging along I think because once we start working on the meat of the project on the instructor side, I think it will be clearer...

**Comment by phlco** [comment]
Closing for now! :+1:
