### ISSUE TITLE
Having trouble sending form to the correct controller

### ISSUE THREAD

**Issue by chaddpaul** [godot-packers/quiz_app#30]
We have a name spacing issue and It is causing ERD problems...How can we create a new quizish object and relate it to a quiz?

**Comment by ghost** [comment]
@chaddpaul this issue is terrible! What is a "quizish" object? And you need to relate it to a quiz?

In absence of better information, it seems to me like the answer to your question is:

``` ruby
qzsh = Quizish.new
qzsh.quiz = Quiz.first
```
