### ISSUE TITLE
Authentication Issues

### ISSUE THREAD

**Issue by krismacfarlane** [godot-packers/quiz_app#8]
We are trying to figure out how to correctly do instructor/student authentication. 

``` ruby
class SessionsController < ApplicationController

  def new
  end

  def create
    # handle the lookup and auth
    if(params[:title] == 'instructor')
      instructor = Instructor.find_by({email: params[:email]})

      if instructor && instructor.authenticate_instructor(params[:password])
        session[:instructor_id] = instructor.id
        redirect_to '/instructors/index'
      end
    elsif(params[:title] == 'student')
      student = Student.find_by({email: params[:email]})

      if student && student.authenticate_student(params[:password])
        session[:student_id] = student.id
        redirect_to '/students/index'
      end
    else
      redirect_to root_path
    end
  end

  def destroy
  end

end
```

``` ruby
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_instructor
    @current_instructor ||= Instructor.find(session[:instructor_id]) if session[:instructor_id]
  end

  def current_student
    @current_student ||= Student.find(session[:student_id]) if session[:student_id]
  end

  # makes current_instructor available in our views
  helper_method(:current_instructor)
  helper_method(:current_student)

  def authenticate_instructor
    redirect_to '/login' unless current_instructor
  end

  def authenticate_student
    redirect_to '/login' unless current_student
  end

end
```

What should our students_controller.rb and instructors_controller.rb look like? It keeps returning an error about missing a student#create thing, but it's also not reading in any password params.

**Comment by krismacfarlane** [comment]
``` ruby
  def authenticate_student
    redirect_to '/login' unless current_student
  end
```

This method is within our application_controller.rb, but when we try to call it within students_controller.rb it is saying that it is an undefined method.

**Comment by phlco** [comment]
You shouldn't have a path called `/instructors/index'` The path to your index action in your controller should just be `/instructors`

Have you gotten authentication to work with Students OR Instructors first? It's easier to do one thing at a time.

**Comment by phlco** [comment]
You haven't pushed any new code to github in 18 hours so it's very difficult to see what you're working on. Please push up new changes!

**Comment by krismacfarlane** [comment]
I think we figured out the issue...stay tuned! Pushing code now.

**Comment by phlco** [comment]
Great. If you solve something please explain what you did!

**Comment by krismacfarlane** [comment]
We should've been calling the method 'authorize_student' or 'authorize_instructor', since 

``` ruby
if instructor && instructor.authenticate(params[:password])
        session[:instructor_id] = instructor.id
        redirect_to ''
end
```

is the correct way to write it in instructors_controller.rb. We didn't realize that .authenticate is a bcrypt method.

**Comment by phlco** [comment]
plus :100:
